import 'package:flutter/material.dart';

class AppLanguage extends ChangeNotifier{
  final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'splashScreenTitle': 'Welcome',
      'InformationsPersonnellesTitle': 'Personal Informations',
      'CompetencesTitle': 'Skills',
      'FormationAcademiqueTitle': 'Academic Training',
      'ExperiencesProfessionnellesTitle': 'Professional Experiences',
      'ProjetsAcademiquesTitle': 'Academic Projects',
      'CertificationsTitle': 'Certifications',
      'LanguesTitle': 'Languages',
      'InteretsTitle': 'Interests',
      'myName': 'Omar Chebbi',
      'descProfil':'Student in computer engineering specializing in Software Engineering and Decision Computing at the International Institute of Technologies of Sfax (IIT)',
      'mapTitle': "See IIT on the map",
      'tel':'Call me',
      'mail': 'Send me an email',
      'LinkedIn':'LinkedIn profil',
      'git': 'GitHub profil',
      'portfolio': 'Visit my portfolio' ,
      'cf': 'Functional Skills',
      'ct':'Technical Skills',
      'lp':'Programming Languages',
      'FrameworksLibrariesTitle': 'Frameworks/Libraries',
      'DatabaseManagementSystemsTitle': 'Database Management Systems',
      'EngineeringTitle': 'Software Engineering and Business Intelligence',
      'EngineeringSubtitle': '2022 – Present | International Institute of Technology of Sfax (IIT)',
      'BigDataTitle': 'Bachelor in Big Data and Data Analysis - High Honors',
      'BigDataSubtitle': '2019 – 2022 | Higher Institute of Computer Science and Multimedia of Sfax (ISIMS)',
      'HighSchoolDiplomaTitle': 'High School Diploma, Technical Sciences - Honors',
      'HighSchoolDiplomaSubtitle': '2019 | Gremda High School, Sfax',
      'ExperienceProfessionnellesTitle': 'Professional Experiences',
      'DataClassificationExtractionTitle': 'Data Classification and Extraction',
      'DataClassificationExtractionSubtitle': 'Machine Learning Internship',
      'IOTPlatformProjectTitle': 'IOT Agriculture Platform with MEAN Stack',
      'IOTPlatformProjectSubtitle': 'End-of-Studies Project',
      'BusinessAnalyticsPowerBITitle': 'Business Analytics with PowerBI',
      'BusinessAnalyticsPowerBISubtitle': 'Applied Training Project',
      'Duration': 'Duration:',
      'Location': 'Location:',
      'SearchHint': 'Search...',
      'agrh': 'Hotel Reservation Management Application',
      'agrh_desc': 'Design and development of a hotel reservation management application with Laravel, Vue.js, and MySQL',
      'iit':'International Institute of Technology Sfax',
      'isims':"Higher Institute of Computer Science and Multimedia of Sfax",
      'hotelReservationManagementApp': 'Hotel Reservation Management Application',
      'hotelReservationManagementAppDescription': 'Design and development of a hotel reservation management application with Laravel, Vue.js, and MySQL',
      'fastFoodOrderingApp': 'Fast Food Ordering Application',
      'fastFoodOrderingAppDescription': 'Design and development of a fast food ordering and tracking application with .NET and SQL Server',
      'onlineSalesApp': 'Online Sales Application',
      'onlineSalesAppDescription': 'Design and development of an online sales and merchandise tracking application with native PHP and MySQL',
      'carRentalApp': 'Online Car Rental Application',
      'carRentalAppDescription': 'Design and development of an online car rental management application with Symfony and MySQL',
      'Arabe': 'Arabic',
      'Français': 'French',
      'Anglais': 'English',
      'Native': 'Native',
      'Intermediate': 'Intermediate',
      'Advanced': 'Advanced',
      'Muscle Building': 'Muscle Building',
      'Camping': 'Camping',
      'Video Games': 'Video Games',
      'Technology': 'Technology',
      'Music': 'Music',
      'Sport': 'Volleyball',
      'CodeQRTitle':'Share App',
      'DarkMode': 'Dark Mode',
      'DayMode': 'Day Mode',

    },
    'ar': {
      'splashScreenTitle': 'مرحباً',
      'InformationsPersonnellesTitle': 'معلومات شخصية',
      'CompetencesTitle': 'مهارات',
      'FormationAcademiqueTitle': 'التكوين الأكاديمي',
      'ExperiencesProfessionnellesTitle': 'الخبرات المهنية',
      'ProjetsAcademiquesTitle': 'المشاريع الأكاديمية',
      'CertificationsTitle': 'الشهادات',
      'LanguesTitle': 'اللغات',
      'InteretsTitle': 'الاهتمامات',
      'myName': 'عمر الشابي',
      'descProfil':' طالب في هندسة الحاسوب تخصص هندسة البرمجيات وحوسبة القرارات بالمعهد الدولي للتكنولوجيات بصفاقس ',
      'mapTitle': 'انظر على الخريطة',
      'tel':'اتصل بي',
      'mail': 'ارسل لي بريد الكتروني',
      'LinkedIn':'LinkedIn ملفي الشخصي ب',
      'git': 'GitHub ملفي الشخصي ب',
      'portfolio': 'قم بزيارة محفظتي' ,
      'cf': 'المهارات الوظيفية',
      'ct':'مهارات تقنية',
      'lp':'لغات البرمجة',
      'FrameworksLibrariesTitle': 'الإطارات / المكتبات',
      'DatabaseManagementSystemsTitle': 'أنظمة إدارة قواعد البيانات',
      'EngineeringTitle': 'هندسة البرمجيات والذكاء الاصطناعي',
      'EngineeringSubtitle': '2022 – الحالي | المعهد الدولي للتكنولوجيا بصفاقس (IIT)',
      'BigDataTitle': 'ليسانس في البيانات الضخمة وتحليل البيانات - بميزة كبيرة',
      'BigDataSubtitle': '2019 – 2022 | المعهد العالي للحاسوب والملتيميديا بصفاقس (ISIMS)',
      'HighSchoolDiplomaTitle': 'شهادة البكالوريا في العلوم التقنية - بميزة جيدة',
      'HighSchoolDiplomaSubtitle': '2019 | ثانوية قرمدة، صفاقس',
      'ExperienceProfessionnellesTitle': 'التجارب المهنية',
      'DataClassificationExtractionTitle': 'تصنيف واستخراج البيانات',
      'DataClassificationExtractionSubtitle': 'تدريب على تعلم الآلة',
      'IOTPlatformProjectTitle': 'منصة الزراعة الذكية بتقنية MEAN Stack',
      'IOTPlatformProjectSubtitle': 'مشروع التخرج',
      'BusinessAnalyticsPowerBITitle': 'تحليلات الأعمال باستخدام PowerBI',
      'BusinessAnalyticsPowerBISubtitle': 'مشروع التدريب التطبيقي',
      'Duration': 'المدة:',
      'Location': 'الموقع:',
      'SearchHint': 'بحث...',
      'iit':'المعهد الدولي للتكنولوجيا بصفاقس',
      'isims':"المعهد العالي للإعلامية والملتيميديا بصفاقس",
      'hotelReservationManagementApp': 'تطبيق إدارة حجز الفنادق',
      'hotelReservationManagementAppDescription': 'تصميم وتطوير تطبيق إدارة حجوزات الفنادق باستخدام Laravel وVue.js وMySQL',
      'fastFoodOrderingApp': 'تطبيق طلبات الوجبات السريعة',
      'fastFoodOrderingAppDescription': 'تصميم وتطوير تطبيق لإضافة ومتابعة طلبات الوجبات السريعة باستخدام .NET و SQL Server',
      'onlineSalesApp': 'تطبيق المبيعات عبر الإنترنت',
      'onlineSalesAppDescription': 'تصميم وتطوير تطبيق لبيع ومتابعة البضائع باستخدام PHP الأصلي و MySQL',
      'carRentalApp': 'تطبيق تأجير السيارات عبر الإنترنت',
      'carRentalAppDescription': 'تصميم وتطوير تطبيق لإدارة تأجير السيارات باستخدام Symfony و MySQL',
      'Arabe': 'عربي',
      'Français': 'فرنسي',
      'Anglais': 'إنجليزي',
      'Native': 'اللغة الأم',
      'Intermediate': 'متوسط',
      'Advanced': 'متقدم',
      'Muscle Building': 'بناء العضلات',
      'Camping': 'التخييم',
      'Video Games': 'ألعاب الفيديو',
      'Technology': 'تقنية',
      'Music': 'موسيقى',
      'Sport': 'الكرة الطائرة',
      'CodeQRTitle':'شارك التطبيق',
      'DarkMode': 'الوضع الليلي',
      'DayMode': 'الوضع النهاري',


    },
    'fr': {
      'splashScreenTitle': 'Bienvenue',
      'InformationsPersonnellesTitle': 'Informations Personnelles',
      'CompetencesTitle': 'Compétences',
      'FormationAcademiqueTitle': 'Formation Académique',
      'ExperiencesProfessionnellesTitle': 'Expériences Professionnelles',
      'ProjetsAcademiquesTitle': 'Projets Académiques',
      'CertificationsTitle': 'Certifications',
      'LanguesTitle': 'Langues',
      'InteretsTitle': 'Intérêts',
      'myName': 'Omar Chebbi',
      'descProfil':'Étudiant en génie informatique spécialité en Génie Logiciel et Informatique Décisionnelle à Institut International de Technologies de Sfax (IIT)',
      'mapTitle': "Voir l'IIT sur la carte",
      'tel':'Appelez-moi',
      'mail': 'Envoie-moi un email',
      'LinkedIn':'profile LinkedIn',
      'git': 'profile GitHub',
      'portfolio': 'Visitez mon portfolio' ,
      'cf': 'Compétences Fonctionnelles',
      'ct':'Compétences Techniques',
      'lp':'Langages de programmation',
      'FrameworksLibrariesTitle': 'Frameworks/Libraries',
      'DatabaseManagementSystemsTitle': 'Systèmes de Gestion de Base de Données',
      'EngineeringTitle': 'Ingénierie Génie Logiciel et Informatique Décisionnelle',
      'EngineeringSubtitle': '2022 – Présent | Institut International de Technologies de Sfax (IIT)',
      'BigDataTitle': 'Licence Big Data et Analyse de Données - Mention Très Bien',
      'BigDataSubtitle': '2019 – 2022 | Institut Supérieur d\'Informatique et de Multimédia de Sfax (ISIMS)',
      'HighSchoolDiplomaTitle': 'Baccalauréat Section Sciences Techniques - Mention Assez Bien',
      'HighSchoolDiplomaSubtitle': '2019 | Lycée Gremda, Sfax',
      'ExperienceProfessionnellesTitle': 'Expériences Professionnelles',
      'DataClassificationExtractionTitle': 'Classification et Extraction des données',
      'DataClassificationExtractionSubtitle': 'Stage d\'initiation en Machine Learning',
      'IOTPlatformProjectTitle': 'Plateforme IOT pour l\'Agriculture avec MEAN Stack',
      'IOTPlatformProjectSubtitle': 'Projet de Fin d\'Études',
      'BusinessAnalyticsPowerBITitle': 'Analyse d\'Affaires avec PowerBI',
      'BusinessAnalyticsPowerBISubtitle': 'Projet de Formation Appliquée',
      'Duration': 'Durée:',
      'Location': 'Localisation:',
      'SearchHint': 'Recherche...',
      'iit':'Institut International de Technologie Sfax',
      'isims':"Institut Supérieur d'Informatique et de Multimédia de Sfax",
      'hotelReservationManagementApp': 'Application de Gestion des Réservations d’Hôtel',
      'hotelReservationManagementAppDescription': 'Conception et développement d’une application de gestion des réservations d’Hôtel avec Laravel, Vue js et MySQL',
      'fastFoodOrderingApp': 'Application des Commandes Fast Foods',
      'fastFoodOrderingAppDescription': 'Conception et développement d’une application d’ajout et suivi des commandes Fast Foods avec .NET et SQL Server',
      'onlineSalesApp': 'Application des Ventes en ligne',
      'onlineSalesAppDescription': 'Conception et développement d’une application de vente et suivi des marchandises avec PHP native et MySQL',
      'carRentalApp': 'Application de Location des Voitures en ligne',
      'carRentalAppDescription': 'Conception et développement d’une application pour gérer les locations des voitures avec Symfony et MySQL',
      'Arabe': 'Arabe',
      'Français': 'Français',
      'Anglais': 'Anglais',
      'Native': 'Langue maternelle',
      'Intermediate': 'Assez bien',
      'Advanced': 'Très bien',
      'Muscle Building': 'Musculation',
      'Camping': 'Camping',
      'Video Games': 'Jeux vidéo',
      'Technology': 'Technologie',
      'Music': 'Musique',
      'Sport': 'Volley-ball',
      'CodeQRTitle':"Partager l'Application",
      'DarkMode': 'Mode Sombre',
      'DayMode': 'Mode Jour',

    },
  };


  String _currentLanguage = 'fr';

  void setLanguage(String languageCode) {
    if (_localizedValues.containsKey(languageCode)) {
      _currentLanguage = languageCode;
      notifyListeners(); // Notify widgets of the change.

    }
  }

  String translate(String key) {
    return _localizedValues[_currentLanguage]?[key] ?? '';
  }
}
